Repository MasterEric/krystara-io-i18n, pull requests merged in 2020-07, with the labels that each got.

#11 Translate tasks.json to French
  fr/tasks.json
Labels: French

#14 Translated platforms.json to French
  fr/platforms.json
Labels: French

#15 Translated privacy.md to French
  fr/privacy.md
Labels: French

#16 Translated pvp.json to French
  fr/pvp.json
Labels: French

#17 English - Remove duplicate keys from events.json.
  en/events.json
Labels: English

#25 Translate events.json to Chinese
  zh/events.json
Labels: Chinese

#13 Translate game.json to Chinese
  zh/game.json
Labels: Chinese

#21 Translated pages.json to Chinese
  zh/pages.json
Labels: Chinese

#24 Translated platforms.json to Chinese
  zh/platforms.json
Labels: Chinese

#27 Translate tasks.json to Chinese
  zh/tasks.json
Labels: Chinese

#28 Translate pvp.json to Chinese
  zh/pvp.json
Labels: Chinese

#29 Translate languages.json to Chinese
  zh/languages.json
Labels: Chinese

#30 Translate home.json to Chinese
  zh/home.json
Labels: Chinese

#31 Translate guildwars.json to Chinese
  zh/guildwars.json
Labels: Chinese

#32 Translate guild.json to Chinese
  zh/guild.json
Labels: Chinese

#36 Updated descriptions in pages.json for Chinese
  zh/pages.json
Labels: Chinese

#60 Translate privacy.md to Italian
  it/privacy.md
Labels: Italian

#59 Translate tasks.json to Italian
  it/tasks.json
Labels: Italian

#58 Translate platforms.json to Italian
  it/platforms.json
Labels: Italian

#51 Translate guildwars.json to Italian
  it/guildwars.json
Labels: Italian

#57 Translate pages.json to Italian
  it/pages.json
Labels: Italian

#54 Translate languages.json to Italian
  it/languages.json
Labels: Italian

#52 Translate home.json to Italian
  it/home.json
Labels: Italian

#47 Translate guild.json to Italian
  it/guild.json
Labels: Italian

#46 Translate events.json to Italian
  it/events.json
Labels: Italian

#45 Translate error.json to Italian
  it/error.json
Labels: Italian

#44 Translate common.json to Italian
  it/common.json
Labels: Italian

#43 Translate game.json to Italian
  it/game.json
Labels: Italian

#53 Translate pvp.json to Italian
  it/pvp.json
Labels: Italian
